# Site settings
title: Pokenoticias
email: pokenoticia@gmail.com
description: "Noticias Pokemon en Espa√±ol"
logo_location: "http://www.stivco.com/random/tats/pokeball.gif"

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://pokenoticias.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true